# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: eshopweb-cicd
trigger:
  - master

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        pool: Default
        steps:
        - task: DotNetCoreCLI@2
          displayName: restore
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
            feedsToUse: select
        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
           command: 'build'
           projects: '**/*.sln'
        - task: DotNetCoreCLI@2
          displayName: Unit-Test
          inputs:
            command: 'test'
            projects: 'tests/Ordering.UnitTests/*.UnitTests.csproj'
        - task: DotNetCoreCLI@2
          displayName: Publish
          inputs:
           command: 'publish'
           publishWebProjects: true
           arguments: '-o $(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          displayName: Publish Artifacts
          inputs:
           PathtoPublish: '$(Build.ArtifactStagingDirectory'
           ArtifactName: RetailApp
          

